### ISSUE TITLE
Doesn't shut down nicely

### ISSUE THREAD

**Issue by morganchristiansson** [lukewaite/logstash-input-cloudwatch-logs#35]
When running `service logstash stop` the cloudwatch_logs input keeps reading events until the init system kills logstash with 9/SIGKILL.

Can a nice shutdown with proper sincedb support be achieved?

**Comment by morganchristiansson** [comment]
I'm concerned about data loss here.... Can graceful shutdown be implemented please?

**Comment by lukewaite** [comment]
Sorry, I missed this ticket being opened somehow.

Can you please confirm the version you're running? I thought this was properly handled in the latest releases.

**Comment by morganchristiansson** [comment]
logstash-input-cloudwatch_logs-1.0.0

Can upgrade to 1.0.1 latest but don't see this mentioned in the release notes?

**Comment by lukewaite** [comment]
No - the change I'm thinking of was in 1.0.0. Upgrading won't gain you anything here.

I'll take another look.

**Comment by lukewaite** [comment]
Are you seeing anything in logs after the SIGINT along the lines of either:
* something about inflight events
* something about the plugin not shutting down

I forget the exact wording, off the top of my head.

**Comment by morganchristiansson** [comment]
Yeah.

```
[2017-09-20T17:01:25,165][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>12682, "stalling_thread_info"=>{"other"=>[{"thread_id"=>57, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/1.9/net/protocol.rb:143:in \`select'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["[cloudwatch_logs][log_stream]"], "id"=>"8c22843b6c1dbf765f64ce96fdf72cc0aaf5ad31-19"}]=>[{"thread_id"=>34, "name"=>"[main]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:121:in \`lock'"}, {"thread_id"=>36, "name"=>"[main]>worker2", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in \`lock'"}, {"thread_id"=>37, "name"=>"[main]>worker3", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in \`lock'"}, {"thread_id"=>38, "name"=>"[main]>worker4", "current_call"=>"[...]/logstash-core/lib/logstash/instrument/metric_store.rb:55:in \`put_if_absent'"}, {"thread_id"=>40, "name"=>"[main]>worker6", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in \`lock'"}, {"thread_id"=>41, "name"=>"[main]>worker7", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in \`lock'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["[cloudwatch_logs][log_stream]"], "id"=>"8c22843b6c1dbf765f64ce96fdf72cc0aaf5ad31-8"}]=>[{"thread_id"=>35, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in \`lock'"}], ["LogStash::Filters::Grok", {"match"=>{"[cloudwatch_logs][log_stream]"=>"(?:[AB]/)?(?<env>[^/]+)/(?<app>[^/]+)/.*"}, "id"=>"8c22843b6c1dbf765f64ce96fdf72cc0aaf5ad31-18"}]=>[{"thread_id"=>39, "name"=>"[main]>worker5", "current_call"=>"[...]/logstash-core/lib/logstash/instrument/metric_store.rb:55:in \`put_if_absent'"}]}}
```

**Comment by morganchristiansson** [comment]
Here's full logs from logstash-plain.log

```
[2017-09-27T12:50:05,383][WARN ][logstash.runner          ] SIGTERM received. Shutting down the agent.
[2017-09-27T12:50:05,389][WARN ][logstash.agent           ] stopping pipeline {:id=>".monitoring-logstash"}
[2017-09-27T12:50:06,432][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
[2017-09-27T12:50:11,460][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>47, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/
logstash-input-beats-3.1.23-java/lib/logstash/inputs/beats.rb:206:in `run'"}, {"thread_id"=>48, "name"=>"[main]<s3", "current_call"=>"[...]/vendor/jruby/lib/ruby/1.9/net/protocol.rb:143:in `select'"}, {"thread_i
d"=>50, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>54, "name"=>"[main]<cloudwatch_logs", "current_call"=
>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["time_iso8601", "time_local", "[cloudwatch_logs][log_stream]"], "id"=>"f085
ca847d54bbdefd00985a0c4faa3240ab6aef-19"}]=>[{"thread_id"=>38, "name"=>"[main]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}, {"thread_id"=>39, "na
me"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}, {"thread_id"=>40, "name"=>"[main]>worker2", "current_call"=>"[...]/logstash-core/lib/lo
gstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["[cloudwatch_logs][log_stream]"], "id"=>"f085ca847d54bbdefd00985a0c4faa3240ab6aef-12"}]=>[{"thread_id"=>
41, "name"=>"[main]>worker3", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}]}}
[2017-09-27T12:50:11,461][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2017-09-27T12:50:16,457][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>48, "name"=>"[main]<s3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/log
stash-input-s3-3.1.5/lib/logstash/inputs/s3.rb:367:in `read'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["time_iso8601", "time_local", "[cloudwatch_logs][log_stream]"], "id"=>"f085ca847d54bbdefd00985a0c4
faa3240ab6aef-19"}]=>[{"thread_id"=>38, "name"=>"[main]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}, {"thread_id"=>39, "name"=>"[main]>worker1", 
"current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:121:in `lock'"}, {"thread_id"=>40, "name"=>"[main]>worker2", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_syn
chronous_queue.rb:147:in `lock'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["[cloudwatch_logs][log_stream]"], "id"=>"f085ca847d54bbdefd00985a0c4faa3240ab6aef-12"}]=>[{"thread_id"=>41, "name"=>"[main]>wor
ker3", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}]}}
[2017-09-27T12:50:21,434][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{}}
```

**Comment by lukewaite** [comment]
Are you ingesting a large number of logs, or via a large number of groups?

At the moment, we're allowing the current iteration of the ingest process to continue, then interrupting before we begin again. 

I think adding a `next if stop?` inside the top of the `groups.each` here might be a good start: https://github.com/lukewaite/logstash-input-cloudwatch-logs/blob/master/lib/logstash/inputs/cloudwatch_logs.rb#L121-L124

Next, I can look at drilling down further and interrupting mid-group, if needed.

**Comment by morganchristiansson** [comment]
Moderate to low nujmber of logs I'd say.

It's worth a try. I'll see if I can find some time to provide further details

**Comment by ryanhartkopf** [comment]
I have this same error with release 1.0.2. I even reduced my workers and batch size to 1 to make sure this wasn't an issue with too many in-flight events to process, but no dice. There are no logs being written to my file output from the time I run `sudo service logstash stop` but it stays stuck anyway.

Here's my logstash.yml:
```
path.data: /var/lib/logstash
pipeline.workers: 1
pipeline.batch.size: 1
path.config: /etc/logstash/conf.d/*.conf
path.logs: /var/log/logstash
```

lambda.conf:
```
input {
    cloudwatch_logs {
        log_group => [ "/aws/lambda/" ]
        log_group_prefix => "true"
        region => "us-west-2"
        type => "lambda"
        sincedb_path => "/dev/null"
    }
}
filter {
    if [type] == "lambda" {
        mutate {
            remove_field => [ "[cloudwatch_logs][ingestion_time]", "[cloudwatch_logs][event_id]" ]
        }
        grok {
            match => { "message" => "%{TIMESTAMP_ISO8601}\t%{UUID:[lambda][request_id]}\t%{GREEDYDATA:message}" }
            overwrite => [ "message" ]
            tag_on_failure => []
        }

        grok {
            match => { "message" => "(?:START|END) RequestId: %{UUID:[lambda][request_id]}" }
            tag_on_failure => []
        }

        grok {
            match => { "message" => "REPORT RequestId: %{UUID:[lambda][request_id]}\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB" }
            tag_on_failure => []
        }
    }
}
output {
    if [type] == "lambda" {
        if "_grokparsefailure" in [tags] {
            file {
                path => "/logs/lambda_fail.log"
            }
        }
        file {
            path => "/logs/lambda.log"
        }
    }
}
```

logstash-plain.log:
```
[2018-02-01T16:31:26,806][WARN ][logstash.runner          ] SIGTERM received. Shutting down the agent.
[2018-02-01T16:31:31,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:31:31,831][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2018-02-01T16:31:36,829][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:31:41,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:31:46,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:31:51,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:31:56,836][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:01,829][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:06,829][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:11,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:16,829][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:21,834][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:26,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:31,829][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:36,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:41,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:46,829][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:51,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-01T16:32:56,833][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<cloudwatch_logs", "current_call"=>"[...]/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:158:in `wait'"}], ["LogStash::Filters::Grok", {"match"=>{"message"=>"REPORT RequestId: %{UUID:[lambda][request_id]}\\tDuration: %{BASE16FLOAT:[lambda][duration]:int} ms\\tBilled Duration: %{BASE16FLOAT:[lambda][billed_duration]:int} ms \\tMemory Size: %{BASE10NUM:[lambda][memory_size]:int} MB\\tMax Memory Used: %{BASE10NUM:[lambda][memory_used]:int} MB"}, "tag_on_failure"=>[], "id"=>"85ca55db5fd88f5f5c061cff4c7b28558e8180bf7c6bc8ddebf09826b328925f"}]=>[{"thread_id"=>28, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
```

syslog:
```
Feb  1 16:31:26 ip-172-31-34-124 systemd[1]: Stopping logstash...
Feb  1 16:32:56 ip-172-31-34-124 systemd[1]: logstash.service: State 'stop-sigterm' timed out. Killing.
Feb  1 16:32:56 ip-172-31-34-124 systemd[1]: logstash.service: Main process exited, code=killed, status=9/KILL
Feb  1 16:32:56 ip-172-31-34-124 systemd[1]: Stopped logstash.
Feb  1 16:32:56 ip-172-31-34-124 systemd[1]: logstash.service: Unit entered failed state.
Feb  1 16:32:56 ip-172-31-34-124 systemd[1]: logstash.service: Failed with result 'signal'.
```
