### ISSUE TITLE
determine_start_position barfs with a number

### ISSUE THREAD

**Issue by tedder** [lukewaite/logstash-input-cloudwatch-logs#38]
I tried using this for a start position. Note there are no quotes on the number:

```
  # start one hour ago
  start_position => 3600
```

Here's the error/fail:

```
Error: undefined method `-' for "1504201621152":String
Exception: NoMethodError
Stack: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-cloudwatch_logs-1.0.1/lib/logstash/inputs/cloudwatch_logs.rb:173:in `determine_start_position'
Stack: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-cloudwatch_logs-1.0.1/lib/logstash/inputs/cloudwatch_logs.rb:173:in `determine_start_position'
```

If I quote it, I get this error:

```
[2017-08-31T18:07:54,634][ERROR][logstash.agent ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: start_position '3600' is invalid! Must be `beginning`, `end`, or an integer.>,
```

**Comment by lukewaite** [comment]
This is resolved in the just-tagged v1.0.2.
